### ISSUE TITLE
[항목 23-2] 165p 패키징 유연성이란?

### ISSUE THREAD

**Issue by hwayoungBaek** [cppmm-developer/effective_cpp#23]
165p 두번째 단락에서 WebBrower구성할 때 미벰버 함수를 사용하면 패키징 유연성이 높아지는 장점이 있다고 설명하고 있습니다. 여기서 말하는 '패키징 유연성'이 뭔지 궁금합니다.

**Comment by chae9606** [comment]
'패키징 유연성'은 프로그램의 코드와 라이브러리를 모듈화하고 패키징하는 유연성을 의미합니다.
이는 소프트웨어 개발 및 유지보수 관점에서 중요합니다!

프로그램의 코드와 라이브러리를 적절히 분리하고, 적절한 디렉토리 구조로 구성해 쉽게 패키징할 수 있게 해야합니다. 이를 통해 코드의 '재사용성'이 높아지고 유지보수가 용이해 집니다.
그리고, 다양한 운영체제와 플랫폼에서 프로그램을 실행할 수 있도록 하는 것이 중요합니다.
예를 들어, C++로 짠 코드가 WIndow와 Linux 환경에서 모두 실행될 수 있도록 해야 합니다.

그럼 멤버 함수 대신 비멤버 함수를 사용하면 왜 패키징 유연성이 높아질까요? Chat GPT에게 물어봤습니다.
Using non-member, non-friend functions instead of member functions in C++ can increase packaging flexibility by allowing the implementation of a class to be separated from its interface.

Packaging flexibility refers to the ability to organize and package code into logical units, such as classes or libraries, that can be independently developed, tested, and maintained. In a well-designed software system, each package should have a well-defined interface that specifies the behavior and capabilities of the package, while hiding the implementation details from the rest of the system.

Member functions are tightly coupled to the class they belong to and have access to its private members, which can make it more difficult to change the implementation of the class without affecting its interface. On the other hand, non-member, non-friend functions are not bound to the class and can only access its public interface, which makes them more flexible and independent.

By using non-member, non-friend functions, you can write generic algorithms that can operate on objects of multiple classes that have a similar interface, without being tightly coupled to any of them. This promotes code reuse and makes it easier to maintain and evolve the codebase over time.

Additionally, using non-member, non-friend functions can also help with encapsulation by limiting the access to the class's private members only to its member functions, which can help prevent unintended modifications to the class's internal state.

**Comment by hwayoungBaek** [comment]
저는 다시 Chat GPT에게 번역을 맡겼습니다 ㅋㅋㅋ(아래에 공유합니다.)

아래 내용만 보면 코드 내부 클래스 관점에서의 패키징 유연성은 캡슐화랑도 큰 맥락을 같이 하는 것 같네요!
```
C++에서 멤버 함수가 아닌 비멤버, 비프렌드 함수를 사용하면 클래스의 구현과 인터페이스를 분리할 수 있어 패키징 유연성을 높일 수 있습니다.

패키징 유연성이란 코드를 클래스나 라이브러리와 같은 논리적 단위로 조직화하고 패키징할 수 있는 능력을 말합니다. 잘 설계된 소프트웨어 시스템에서 각 패키지는 잘 정의된 인터페이스를 가져야 하며 패키지의 동작과 능력을 지정하면서 시스템의 나머지 부분에서는 구현 세부 정보를 숨겨야 합니다.

멤버 함수는 속한 클래스에 강하게 결합되어 있고, 해당 클래스의 private 멤버에 액세스할 수 있으므로 클래스의 구현을 변경하는 것이 인터페이스에 영향을 미치는 것이 더 어려울 수 있습니다. 반면, 비멤버, 비프렌드 함수는 클래스에 바인딩되지 않으며, public 인터페이스에만 액세스할 수 있으므로 더 유연하고 독립적입니다.

비멤버, 비프렌드 함수를 사용하면 비슷한 인터페이스를 가진 여러 클래스의 객체에서 작동할 수 있는 일반적인 알고리즘을 작성할 수 있으며, 이들 중 어떤 것에도 강하게 결합되지 않습니다. 이는 코드 재사용을 촉진하고 코드베이스를 유지 관리하고 발전시키기 쉽게 만듭니다.

또한, 비멤버, 비프렌드 함수를 사용하면 클래스의 private 멤버에 대한 액세스를 멤버 함수에만 제한하여 캡슐화에 도움이 될 수 있습니다. 이는 클래스의 내부 상태를 의도하지 않은 수정으로부터 방지하는 데 도움이 됩니다.
```

코드와 라이브러리 분리, 디렉토리 구조, 운영체제와 플랫폼 지원 등에 관련된 내용은 회사 플젝에서도 같이 살펴보면 좋을 것 같아요! 현재 개발 중인 플랫폼이 얼마나 패키징이 유연하게 가능한지요.
